version: "3.9"

services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.5.4
    container_name: keycloak
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    volumes:
      # Đặt file realm JSON export sẵn trong thư mục ./realm-export (ví dụ: my-realm.json)
      - ./realm-export:/opt/keycloak/data/import
    ports:
      - "8180:8080"
    command: start-dev --import-realm

networks:
  keycloak-net:
    driver: bridge

