server:
  port: 8080

spring:
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: nuxt-frontend
            client-secret: 1234567890
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope:
              - openid
              - profile
              - email
              - roles
      resourceserver:
        jwt:
          # Keycloak tự động expose JWKS endpoint
          jwk-set-uri: http://localhost:8080/realms/myapp/protocol/openid-connect/certs
          issuer-uri: http://localhost:8080/realms/myapp

app:
  cors:
    allowed-origins: http://localhost:3000