server:
  port: 8081

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          # Keycloak tự động expose JWKS endpoint
          jwk-set-uri: http://localhost:8080/realms/myapp/protocol/openid-connect/certs
          issuer-uri: http://localhost:8080/realms/myapp

app:
  cors:
    allowed-origins: http://localhost:3000