server:
  port: 8080

spring:
  security:
    oauth2:
      client:
        registration:
          keycloak:
            provider: keycloak
            client-id: nuxt-frontend
            client-secret: 1234567890
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope:
              - openid
              - profile
              - email
              - roles
        provider:
          keycloak:
            issuer-uri: http://localhost:8180/realms/chopper
            authorization-uri: http://localhost:8180/realms/chopper/protocol/openid-connect/auth
            token-uri: http://localhost:8180/realms/chopper/protocol/openid-connect/token
            jwk-set-uri: http://localhost:8180/realms/chopper/protocol/openid-connect/certs
            user-info-uri: http://localhost:8180/realms/chopper/protocol/openid-connect/userinfo
            user-name-attribute: preferred_username
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/realms/chopper
          jwk-set-uri: http://localhost:8180/realms/chopper/protocol/openid-connect/certs

app:
  frontend-url: http://localhost:3000
  post-login-redirect: http://localhost:3000/dashboard
  post-logout-redirect: http://localhost:3000

logging:
  level:
    org.springframework.security: DEBUG   # Bỏ ở production
    com.taitd.auth: DEBUG